# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55d9c570ab47193e60a7a2cfd0b695f401c4347e7b19b16d39635cad87d649809eee6b7e192273d1616ed5dfe3b0ffa9ffad1f1791bfa06db741b3c9d96ade4c

test:
  secret_key_base: 6bac359b0e1623eea3246ce685c15d26125982ca15841d72ba43ee74a10a1f7e9b3ff56ca4c841abfb88c13ca75b658ce53bd19814ef6274d8506794e4a9c227

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
